# 0. 텐서플로우??

텐서플로우는 구글이 직접적으로 개발에 관여한 딥러닝을 위한 모듈  
따라서, google colab에서 활용할 경우 세션 설정에 따라 CPU와 GPU 버전 모두 추가 설치 없이 최신 버전 사용 가능  
(단, v1 사용을 위해 추가적인 설정 필요)

v1 사용을 위해서는 아래와 같은 코드의 실행을 통해 Downgrade를 할 필요가 있음

```
!pip install tensorflow-gpu==1.15
!pip install keras==2.3.1
```



### 코랩이 아닌 우분투(pc,server)를 활용할 경우 필요한 설치과정  
anaconda -> virtualenv -> tensorflow install



- > pytorch 역시 최신 버전이 설치되어 있으나, Graph 기반의 연산을 위해 Geometric을 사용 할 경우 cuda 버전의 차이로 호환되는 모듈로의 세부 조율이 필요



```
import torch
torch.__version__
```





In [ ]:
import torch
torch.__version__

'1.12.1+cu113'

# 1. 텐서플로우 기초

In [ ]:
import tensorflow as tf

print('tensorflow version = ', tf.__version__)

tensorflow version =  2.8.2


## 1.1 텐서플로우 기초 자료형

In [ ]:
# Type
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int32)
number2 = tf.Variable(123, tf.int32)
floating = tf.Variable(3.567, tf.float32)
print(string, '\n', number, '\n', floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> 
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> 
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [ ]:
print(number + number2)

tf.Tensor(447, shape=(), dtype=int32)


In [ ]:
# Demention
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>


In [ ]:
# Reshape

tensor1 = tf.ones([1,2,9])
tensor2 = tf.reshape(tensor1, [2,9,1])
tensor3 = tf.reshape(tensor2, [3, -1])

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(1, 2, 9), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]], shape=(2, 9, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(3, 6), dtype=float32)


In [ ]:
# Slice(Handling)
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tensor)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>


In [ ]:
# Now lets select some different rows and columns from our tensor

row1 = tensor[0]  # selects the first row
print(row1)

three = tensor[1,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_3_and_4 = tensor[2:4, 0]
print(column_1_in_row_3_and_4)


tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([11 16], shape=(2,), dtype=int32)


## 1.2 텐서플로우 동작

In [ ]:
# Create a Tensor.
hello = tf.constant("hello world")
print(hello)

# To access a Tensor value, call numpy().
print(hello.numpy())

tf.Tensor(b'hello world', shape=(), dtype=string)
b'hello world'


In [ ]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

# Various tensor operations.
# Note: Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [ ]:
print(a+b+c)
print((a+b+c).numpy())

tf.Tensor(10, shape=(), dtype=int32)
10


In [ ]:
# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [ ]:
# Matrix multiplications.
matrix1 = tf.constant([[2., 1.], [1., 2.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[17., 20.],
       [19., 22.]], dtype=float32)>

In [ ]:
# Convert Tensor to Numpy.
new = product.numpy()
print(type(new))
new

<class 'numpy.ndarray'>


array([[17., 20.],
       [19., 22.]], dtype=float32)