# 6강 파이토치 기초
## 이번 강의에서 다룰 내용
1. 텐서 소개: 토치에서의 머신 러닝 딥러닝의 기본 데이터 구조
2. 텐서 생성: 텐서로 거의 모든 종류의 데이터를 표현 가능(이미지, 텍스트, 숫자 테이블, 그래프 등)
3. 텐서 연산 및 그라디언트: 텐서로 여러가지 연산을 수행
4. 텐서 다루기: 모양의 불일치 처리, 인덱싱
5. Pytorch 텐서와 Numpy 같이 사용하기

텐서 소개 이전에 파이썬 코드에서 라이브러리를 사용하려면 `import`라는 명령어로 사용할 라이브러리를 가져와야 한다.

In [7]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())
print(torch.cuda.device_count())

1.11.0+cu113
True
Tesla T4
1


In [8]:
x = torch.Tensor(3,4).cuda()
print(x)

tensor([[-1.0699e-07,  0.0000e+00,  8.2741e+08,  3.4449e+24],
        [ 1.6604e+19,  8.8593e+11,  2.7233e+20,  7.7782e+31],
        [ 6.0409e+28,  1.8372e+28,  7.2537e+28,  1.5434e+25]], device='cuda:0')


파이토치 프레임워크 구성
* torch : 메인 네임스페이스로 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조를 가진다.
* torch.autograd : 자동 미분을 위한 함수들이 포함한다.
* torch.nn : 신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어 있다.
* torch.optim : 확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘을 제공한다.
* torch.utils.data : SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어 있다.
* 더 자세한건 https://pytorch.org/docs/stable/index.html

## 1. 텐서 소개
텐서는 머신 러닝의 기본 데이터 블록으로 텐서는 데이터를 모두 숫자표현으로 바꾸는 것을 목표로 한다.
예를 들면, 이미지에는 RGB라는 색상의 3채널과 픽셀의 높이 너비가 있는데 이를 [3,224,224] 모양의 텐서로 표현할 수 있다.
![img](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

텐서(Tensor)는 수학과 물리에서 `다차원의 배열`을 말하는데 파이토치에서도 비슷하게 쓴다. 중요한 내용은 아니지만 각 데이터의 형태에 따라 부르는 명칭이 약간씩 다르다는 것을 기억하자.
간단한 숫자 하나를 `스칼라(Scalar)`라고 하고
1차원 배열 즉, 여러 숫자의 나열을 `벡터(Vector)`라고 한다.
2차원 배열 즉, 행과 열을 가진 2차원 배열을 `행렬(Matrix)`라고 한다.
아래 그림으로 설명한 내용을 바로 파악할 수 있을 것이다.
![img](https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMTM0/MDAxNTkwMzc4MTY4MDQy.iOzxIfhew8Bsto7uqNW3QYj-k9bysF775jXYLECD6bwg.uMJ87NPURvklkXF2TXFnygaSnc32erHm_mXbnKgvO24g.PNG.nabilera1/image.png?type=w800)

우리가 딥러닝을 하기위해서 텐서를 사용하는 이유는 실세계의 데이터를 텐서로 표현할 수 있기 때문이다.
* 테이블 데이터 : 2D Tensor (샘플, 피쳐)
* 시계열, 시퀀스 데이터: 3D tensor (샘플, 타임 스탭, 피쳐)
* 이미지 : 4D tensor (샘플, 세로, 가로, 채널)
* 비디오 : 5D tensor (샘플, 프레임, 세로, 가로, 채널)

그러면, 직접 텐서를 만들어보자.

##2. 텐서 생성

In [16]:
# 스칼라(단일 숫자) 텐서 생성
t1 = torch.tensor(7)
t1
# 스칼라는 단일 숫자이고, 텐서로 말하면 0차원 텐서이다.

tensor(7)

In [17]:
t1.ndim

0

In [18]:
# 스칼라(단일 숫자 소수) 텐서 생성
t2 = torch.tensor(4.)
t2

tensor(4.)

`4.`는 `4.0`의 줄임말이다. 부동 소수점 숫자를 생성하려는 Python(및 PyTorch)을 나타내는 데 사용된다. 텐서의 `dtype` 속성을 확인하여 이를 확인할 수 있다.

데이터 타입을 출력해보면 `float32`라는 것을 확인할 수 있다.

In [20]:
print(t2.dtype)
print(t2.ndim)

torch.float32
0


In [25]:
# 여러개의 숫자를 포함하는 텐서(벡터) 생성
t3 = torch.tensor([1., 2, 3, 4])
print(t3)
print(t3.dtype)
print(t3.ndim)

tensor([1., 2., 3., 4.])
torch.float32
1


In [24]:
# 행렬 모양의 텐서 생성
t4 = torch.tensor([[5, 6], 
                   [7, 8], 
                   [9, 10]])
t4
print(t4)
print(t4.dtype)
print(t4.ndim)

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])
torch.int64
2


In [30]:
# 몇차원의 텐서일까요?
t5 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
t5

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [31]:
t5.ndim

3

텐서는 각 차원을 따라 여러 차원과 다른 길이를 가질 수 있다.

텐서의 `.shape` 속성을 사용하여 각 차원의 길이를 검사할 수 있다.

In [33]:
t5.shape

torch.Size([1, 3, 3])

![img](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

### 난수 텐서
우리는 이제 데이터에 따른 텐서의 형태를 파악했습니다. 머신 러닝 모델은 텐서로 변환된 데이터 내의 패턴을 찾을 겁니다.
대부분의 경우 텐서를 직접 만드는 경우는 드물 겁니다. (데이터를 얻어서 텐서로 변환하기 때문)
대신, 무작위 텐서로 시작해 더 잘표현하기위해 이 난수를 조정하면서 알맞은 값으로 최적화하는 과정을 수행하는 경우가 많다. 예를들면, 모델의 학습 파라미터(가중치)
따라서 난수 텐서를 만드는 방법을 알아보자.

In [36]:
#난수 텐서 생성 size의 값들을 조절하며 원하는 모양의 난수 텐서를 생성 가능
r_t = torch.rand(size=(3,4))
r_t, r_t.dtype

(tensor([[0.0567, 0.6230, 0.2767, 0.5098],
         [0.1010, 0.3361, 0.3517, 0.6870],
         [0.4449, 0.0943, 0.6287, 0.2887]]), torch.float32)

In [38]:
r_t2 = torch.rand(size=(224,224,3))
r_t2, r_t2.shape, r_t2.ndim

(tensor([[[0.1582, 0.5780, 0.2726],
          [0.8758, 0.2811, 0.4875],
          [0.0950, 0.2536, 0.3605],
          ...,
          [0.0388, 0.6037, 0.9951],
          [0.0527, 0.7784, 0.1126],
          [0.7237, 0.3266, 0.1519]],
 
         [[0.0783, 0.5602, 0.6929],
          [0.5420, 0.4282, 0.9296],
          [0.4230, 0.3405, 0.0943],
          ...,
          [0.0516, 0.4254, 0.3576],
          [0.2775, 0.9349, 0.1919],
          [0.4015, 0.2137, 0.7190]],
 
         [[0.1924, 0.2208, 0.9597],
          [0.0980, 0.9052, 0.9403],
          [0.0215, 0.1646, 0.1339],
          ...,
          [0.3883, 0.0749, 0.0449],
          [0.8462, 0.0185, 0.4668],
          [0.2415, 0.2470, 0.7964]],
 
         ...,
 
         [[0.6930, 0.3830, 0.6892],
          [0.5595, 0.6943, 0.4835],
          [0.4801, 0.9106, 0.1346],
          ...,
          [0.5981, 0.9161, 0.3332],
          [0.0180, 0.8866, 0.5318],
          [0.0551, 0.5563, 0.6963]],
 
         [[0.2969, 0.9677, 0.4747],
          [0

### 0과1로 채워진 텐서
때때로 0이나 1로 채워진 텐서를 사용해야할 일이 있습니다. 예를들면, 특정한 값을 0으로 채워 학습하지 않도록 세팅하는 상황
* 0으로 채워넣는 텐서는 `torch.zeros()`를 사용하고,
* 1로 채워넣는 텐서는 `torch.ones()`를 사용한다.

In [42]:
#모두 0으로 채워진 텐서를 생성한다. 
#난수 텐서 생성 방법과 마찬가지로 size를 사용자가 원하는데로 조절 가능
z_t = torch.zeros(size=(2, 3))
z_t, z_t.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), torch.float32)

In [43]:
#모두 0으로 채워진 텐서를 생성한다. 
#난수 텐서 생성 방법과 마찬가지로 size를 사용자가 원하는데로 조절 가능
z_t = torch.ones(size=(2, 3))
z_t, z_t.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]), torch.float32)

### 범위 지정 텐서 생성하기
마찬가지로, 0-10, 0-100까지의 숫자를 갖는 텐서를 생성해야하는 경우가 종종 있다.
이런 경우에는 `torch.range()`

In [53]:
r_t=torch.range(start=0,end=9)
r_t, r_t.ndim, r_t.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1, torch.Size([10]))

In [54]:
r_t2=torch.zeros_like(r_t)
r_t2, r_t2.ndim, r_t2.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 1, torch.Size([10]))

In [56]:
r_t3=torch.ones_like(r_t)
r_t3, r_t3.ndim, r_t3.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1, torch.Size([10]))

In [57]:
r_t4=torch.range(start=0,end=10, step=2)
r_t4, r_t4.ndim, r_t4.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


(tensor([ 0.,  2.,  4.,  6.,  8., 10.]), 1, torch.Size([6]))

### 텐서의 데이터 타입
텐서의 데이터 타입이 있는데 데이터 타입은 수치의 정확도, 세밀함을 표현하는데 중요하다. 아무래도 여러번의 곱, 미분 등을 수행하기에 텐서에 할당된 값이 `부동소수점` 데이터 타입인 `float32`를 사용한다. `float16`, `float64`을 사용하기도 한다. 반면, 하나의 데이터의 크기가 세밀하게 표현될 수록 정확한 수치 계산이 가능하지만, 계산량이 증가할 수 있다는 단점이 있다.

텐서가 어디에 위치하는지가 매우 중요하다. 
텐서 연산을 수행할 위치를 결정하는 요소라고도 볼 수 있기 때문이다.

In [61]:
### 텐서의 데이터 타입
f_t = torch.tensor([3.0, 6.0, 9.0])

f_t.shape, f_t.dtype, f_t.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [63]:
#GPU로 텐서 위치 변경
f_t2 = torch.tensor([3.0, 6.0, 9.0]).cuda()

f_t2.shape, f_t2.dtype, f_t2.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [66]:
f_t2 = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

f_t2.shape, f_t2.dtype, f_t2.device

(torch.Size([3]), torch.float16, device(type='cpu'))

## 3. 텐서 연산
딥러닝에서 데이터(이미지, 텍스트, 오디오, 화합물 구조 등)는 텐서로 표현된다.
모델은 텐서를 조사하고 텐서에서 일련의 작업을 수행하여 입력 데이터에 내재된 패턴의 표현을 학습한다.
이러한 모델의 작업에는 여러가지 연산을 사용하는데 `덧셈, 뺄셈, 곱셈, 나눗셈, 행렬곱셈` 이다.

In [78]:
# 4개의 텐서 생성
x = torch.tensor(3.)#변하지않는 값
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)#텐서에서 이루어진 모든연산을 추적하라라는 의미 True를 주면 Autograd가 자동 적용되어 변화도(gradient)를 자동으로 계산할 수 있다.
mu = torch.tensor([1,2,3])
x, w, b, mu

(tensor(3.),
 tensor(4., requires_grad=True),
 tensor(5., requires_grad=True),
 tensor([1, 2, 3]))

In [82]:
x*3, w+1, b/5, mu * mu , torch.matmul(mu,mu)
#단순 곱셈은 [1*1,2*2, 3*3] = [1,4,9]
#행렬곱은 [1*1+2*2+3*3] = [14]

(tensor(9.),
 tensor(5., grad_fn=<AddBackward0>),
 tensor(1., grad_fn=<DivBackward0>),
 tensor([1, 4, 9]),
 tensor(14))

In [83]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [85]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

1차 방정식을 하나 만들어 보려고 한다. `y=wx+b`

In [70]:
y=w*x+b #y=4*3+5
y

tensor(17., grad_fn=<AddBackward0>)

미분, 각도를 계산하기위해 `backward()`라는 함수를 사용할 수 있다.

In [71]:
y.backward()

In [74]:
"dy/dx:" ,x.grad, 'dy/dw:',w.grad, 'dy/db:',b.grad

('dy/dx:', None, 'dy/dw:', tensor(3.), 'dy/db:', tensor(1.))

In [ ]:
x

## 4. 텐서 다루기
앞에서 `torch.matmul()`함수를 보았듯이 텐서의 크기를 변경해야하는 경우가 종종 있다.
텐서의 크기를 변경하는 여러가지 함수가 있는데 이를 소개하겠다.
* torch.reshape(input, shape) #input의 모양을 shape로 바꿔줌
* torch.view(shape) #shape 입력 모양을 반환하지만, 원본 텐서는 그대로 유지
* torch.stack(tensors, dim=0) # 정해진 행, 열을 기준으로 텐서를 쌓음(다만, tensor들의 크기가 같아야함
* torch.squeeze(input) # 모든 차원을 제거해서 1차원으로 반환
* torch.unsqueeze(input, dim) #1차원을 늘려서 반환


In [100]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [101]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
x_view = x.view(1,9)
x_view, x_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [106]:
#여러개의 텐서를 쌓고 싶을때 (dim 바꿔보기)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
x_squeezed=x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [112]:
x_un=x_squeezed.unsqueeze(dim=0)
x_un, x_un.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

### 인덱싱
인덱싱은 텐서의 값에 접근하려고할때 사용되며, 대괄호`[]`와 안의 인덱스 번호를 사용하여 가장 바깥부터 안쪽으로 접근할 수 있다.

In [124]:
#인덱싱 확인을 위한 텐서 하나 정의
x = torch.tensor([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [125]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [126]:
x[0][0]

tensor([1, 2, 3])

In [127]:
x[0][0][0]

tensor(1)

In [129]:
#0번째 차원의 모든 값과 1번째 차원의 0번째 인덱스만 가져옴
x[:, 0]

tensor([[1, 2, 3]])

In [130]:
#0,1차원의 모든 값을 가져오지만, 2번째 차원의 1번째 인덱스만 가져옴
x[:, :, 1]

tensor([[2, 5, 8]])

In [131]:
x [:,  1 ,  1 ]

tensor([5])

In [132]:
x[0,0,:]

tensor([1, 2, 3])

##5. 파이토치 텐서와 넘파이 같이 사용하기
`Numpy`는 파이썬에서 인기있는 수치형 컴퓨팅 라이브러리이다.
파이썬에서 데이터 과학을 위해 Numpy를 지원되는 여러 편리한 라이브러리가 있다.
* 파일 I/O 및 데이터 분석을 위한 [Pandas](https://pandas.pydata.org/)
* 플로팅 및 시각화를 위한 [Matplotlib](https://matplotlib.org/)
* 이미지 및 비디오 처리를 위한 [OpenCV](https://opencv.org/)

그렇기에 토치 텐서와 넘파이 배열의 상호변경을 지원한다.
토치 텐서와 넘파이를 바꾸는 방법은
* `torch.from_numpy(ndraary)`: Numpy 배열 -> Pytorch 텐서
* `torch.Tensor.numpy()`: Pytorch 텐서 ->Numpy 배열

In [137]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [138]:
# 넘파이 배열을 토치 텐서로 변환
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [139]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [140]:
# 당연히 그 반대로도 변환할 수 있다. 토치 텐서를 넘파이 배열로 변환
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])